services:
  - type: web
    name: ltr-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 0
      maxInstances: 1
    disk:
      name: ltr-service-disk
      size: 1GB
      mountPath: /tmp
