name: Deploy to All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run basic health check
        run: |
          python -c "import sys; sys.path.append('.'); from tool_relevance_api import app; print('✅ App imports successfully')"

  deploy-railway:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Deploy to Railway
        run: |
          railway up --service ltr-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  deploy-flyio:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ secrets.FLY_API_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
      - name: Deploy to Fly.io
        run: |
          flyctl deploy --app ltr-service-pro --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  # Render deployment can be added here if you use Render's API or CLI
  # For most users, Render deploys automatically on push to main
