name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests (basic health check)
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from tool_relevance_api import app
        print('✅ App imports successfully')
        "
        
    - name: Build Docker image
      run: |
        docker build -t ltr-service:latest .
        
    - name: Test Docker container
      run: |
        # Start container in background
        docker run -d -p 8000:8000 --name test-container ltr-service:latest
        
        # Wait for startup
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/health || exit 1
        
        # Stop container
        docker stop test-container
        docker rm test-container
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ltr-service:latest ${{ secrets.DOCKER_USERNAME }}/ltr-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ltr-service:latest
        
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true
